### ISSUE TITLE
Add missing groupBy'

### ISSUE THREAD

**Issue by ad-si** [purescript/purescript-arrays#141]
In accordance to `group'` it should first sort the Array and then group it.

Btw: Why not name it `sortAndGroup` or `sortGroup` or `groupSort` or anything more intuitive then `group'`? ^^

**Comment by hdgarrood** [comment]
I'm in favour of renaming `group'`. Although, as I understand it, the sorting is sort of an implementation detail -- I think this function is best described as a function which groups elements like `group` does, except that elements are not required to be consecutive in the array in order to be grouped together. So maybe `groupNonconsecutive` or `groupUnordered` or something?

**Comment by ad-si** [comment]
Yeah, good point! Or maybe `groupTotal`?

**Comment by ad-si** [comment]
Or still simpler: `groupAll`
