### ISSUE TITLE
Deprecate `nub` and rename to `removeDuplicates`

### ISSUE THREAD

**Issue by i-am-the-slime** [purescript/purescript-arrays#223]
I consider myself a fairly competent n-th-language speaker of English. I have never seen the word `nub` being used outside of PS/Haskell, however. For this reason, and motivated by #222 I suggest we deprecate `nub` and rename it to `removeDuplicates`.

Additional "reading": https://impurepics.com/posts/2021-09-26-nub.html

**Comment by sigma-andex** [comment]
Other a bit shorter names would be `distinct` (see e.g. in [Scala](https://www.scala-lang.org/api/3.1.2/scala/collection/immutable/IndexedSeq.html#distinct-0) ) or `deduplicate`.

**Comment by garyb** [comment]
I'm fine with the `isEmpty` idea since it's already used for some collections and `null` for others, and `isEmpty` is an unambiguous obvious choice for the name. But this would take me quite a while to adjust to since there is no precedence for an alternative name for it in PS, and also I'd never remember if it was `uniq`, `uniques`, `deduplicate`, `distinct`, etc. :wink:

**Comment by sigma-andex** [comment]
> But this would take me quite a while to adjust to since there is no precedence for an alternative name for it in PS, and also I'd never remember if it was `uniq`, `uniques`, `deduplicate`, `distinct`, etc.

I would argue that a newcomer would probably search for these words and eventually find it. But it would pretty much surprise me if they would search for `nub` 😉

**Comment by i-am-the-slime** [comment]
> I'd never remember if it was uniq, uniques, deduplicate, distinct, etc. 😉

But at least that'd just be about two tries with autocomplete on 😁

**Comment by i-am-the-slime** [comment]
Okay since there were no strong voices in favour of this, I'll close this.
