### ISSUE TITLE
Relying on transitive maybe dependency

### ISSUE THREAD

**Issue by hdgarrood** [purescript/purescript-arrays#46]
At the moment, `arrays` imports modules from `maybe`, and exports functions which contain `Maybe` types, but `maybe` isn't specified in the bower.json file. Perhaps it would be worth adding it, rather than relying on it being pulled in transitively?

Perhaps it would be useful, if we get a package manager specifically for purescript, for it to enforce this automatically.

**Comment by garyb** [comment]
Hm, I actually did the exact opposite of this when updating the libraries in an attempt to cut down on the cognitive overhead of working out what needs bumping when. Due to the fact we would consider removing a dependency a breaking change, it means adding every dependency explicitly should be unnecessary.

**Comment by hdgarrood** [comment]
Ah, I hadn't considered that you could treat removing dependencies as a breaking change. Ok, I guess it's not an issue then.
