### ISSUE TITLE
unsafeIndex should throw an error

### ISSUE THREAD

**Issue by user471** [purescript/purescript-arrays#57]
```
x :: Array Int
x = []
y = 1 + Data.Array.Unsafe.head x
```
Doesn't have any errors and
```
y == 0
```
I don't think this is a correct behavior

**Comment by joneshf** [comment]
Why? By using `Data.Array.Unsafe` you've said, "Don't worry, I know what I'm doing." And then you proceeded to do the wrong thing. If you don't know with absolute certainty that you actually "know what you're doing," you'd be better of using `Data.Array` rather than using `Data.Array.Unsafe`. Is there a reason you cannot use `Data.Array`?

**Comment by user471** [comment]
> Is there a reason you cannot use Data.Array?

If I am sure the array is not empty, I want to use `head :: [a] -> a`. But if I was wrong I want an error, not a broken state of application. 

Could you show in what case you want an undefined from unsafeIndex?

**Comment by garyb** [comment]
You don't _want_ an undefined from `unsafeIndex` ever, but as @joneshf said, using any `Unsafe` function means you should be totally confident in your reasoning that the function is never going to receive a value outside of its expected parameters, as generally the behaviour of these functions is undefined when that condition is not met.

Part of the reason `unsafeIndex` exists is for high performance needs: `unsafeIndex xs 5` is inlined as `xs[5]`, we can't add a range check to that without a taking a hit.

**Comment by garyb** [comment]
Also the documentation warns you about what will happen if you do misuse `unsafeIndex`:

> Note: this function can cause unpredictable failure at runtime if the index is out-of-bounds.

**Comment by user471** [comment]
If the purpose of this module is high performance, I think it should have an different name, something like `Data.Array.Unsafe.Fast`.
There is `Data.Maybe.Unsafe` where `fromJust` throw an error instead of returning `undefined`
`Data.Array.Unsafe` should have a similar logic otherwise it's confusing.

**Comment by joneshf** [comment]
> But if I was wrong I want an error, not a broken state of application.

Then you should not be using `Data.Array.Unsafe`. You should be using `Data.Array`.

If I can be so bold, it sounds like in your particular use case, you're almost never going to get an empty array, but it might happen on a very rare occasion. This situation still does not warrant using `Data.Array.Unsafe`. You really should not be using `Data.Array.Unsafe` unless you can prove--not guess--that you will never receive bad data.

> Could you show in what case you want an undefined from unsafeIndex?

I cannot, because I would not use `Data.Array.Unsafe` unless I could **prove** for certain that I had the correct data.

**Comment by user471** [comment]
>Then you should not be using Data.Array.Unsafe. You should be using Data.Array.

I would be happy to use `Data.Array` but it doesn't have functions like `head :: Array a -> a`.
The module has bad name, it's not just unsafe as for example `Data.Maybe.Unsafe`, it has a weird unsafety for some specific cases. `Data.Array.Unsafe` should contains same unsafe functions but with error throwing.

**Comment by joneshf** [comment]
Whatever thing you were going to do with `Data.Array.Unsafe.head` you can do the same with `Data.Array.head` if you `map` it instead of using the function directly.

If you wanted to do:

```purescript
module Foo.Unsafe where

  ...
  import Data.Array.Unsafe
  ...

  foo = doSomething (head somePossiblyEmptyArray)
```

Then you can do the same by:

```purescript
module Foo where

  ...
  import Data.Array
  ...

  foo = map doSomething (head somePossiblyEmptyArray)
```

Or if you're hell-bent on having a runtime error, use `Data.Maybe.Unsafe.fromJust` after you call `Data.Array.head`. Then you can keep your runtime errors instead of handling the error at compile time.

**Comment by user471** [comment]
The simplest solution would be creating my own module, but it's not about that. It's about conventions.
There is two options
1) throw an error
2) return `undefined`
Word `Unsafe` should mean only one of them. I suggest it should mean first. If it would have different meaning in every module, it would cost many man-hours of debugging if the future. 
For example, I didn't read documentation of this module because I was sure it mean the same as `Data.Maybe.Unsafe`
	
.

**Comment by sharkdp** [comment]
> Word Unsafe should mean only one of them.

If you want the `Unsafe` modules to have just a single meaning, take "the behaviour of these functions is undefined when the conditions are not met" (paraphrasing @garyb; 'undefined' is the english word, not `undefined`).

As an alternative to @joneshf's suggestion, you could also consider using [Data.NonEmpty](https://github.com/paf31/purescript-nonempty), which provides a `head` function that gives you a non-Maybe value:
``` purescript
head :: forall f a. NonEmpty f a -> a
``` 
By using `NonEmpty Array` instead of `Array`, you are forced to provide a proof that your Array is non-empty *in your code*  (and you never have to resort to any `Unsafe` modules).

**Comment by user471** [comment]
>"the behaviour of these functions is undefined when the conditions are not met"

How does it apply to `Data.Maybe.Unsafe`? Its behavior is pretty defined it throws an error.

Do you think there is no difference in behavior between ```Data.Maybe.Unsafe.fromJust``` and ``` Data.Array.Unsafe.head``` ?

**Comment by garyb** [comment]
No, there is not: `Unsafe` means "misusing these functions results in bad things happening at runtime". "Bad things" covers exceptions, unexpected behaviour due to `undefined`, unexpected behaviour due to an incorrect coercion, etc. Anything that cannot be proven by the compiler.

The distinction you're after will be more apparent in 0.8, as function like `fromMaybe` will instead have the `Partial` constraint and no longer live in `Unsafe`, but discharging the `Partial` constraint will rely on an function in `Partial.Unsafe`.

**Comment by user471** [comment]
>The distinction you're after will be more apparent in 0.8, as function like fromMaybe will instead have the Partial

Is there any description how this `Partial` constrains would work? What would happen here?
```
test = fromJust Nothing
```

**Comment by user471** [comment]
```
getJust :: Partial => Maybe Int -> Int
getJust (Just x) = x

y :: Partial => Int
y = getJust Nothing

main :: forall e. Partial =>  Eff (console :: CONSOLE | e) Unit
main = do
  print $ y
```

I don't understand this Partial constrain. I get the same runtime error and I need to put Partial everywhere, so what is the point?

**Comment by user471** [comment]
The same function for `String` has different behavior.
```
https://github.com/purescript/purescript-strings/blob/master/src/Data/String/Unsafe.js#L13
```
Does someone really think it's a good practice?

**Comment by joneshf** [comment]
No, it does not have different behavior. You are still misunderstanding the purpose of these `Unsafe` modules. Thinking that using an `Unsafe` function means you will get some consistency with the results means that you are misunderstanding what an `Unsafe` function is. All of these functions have the same behavior, namely:

> `Unsafe` means "misusing these functions results in bad things happening at runtime". "Bad things" covers exceptions, unexpected behaviour due to `undefined`, unexpected behaviour due to an incorrect coercion, etc. Anything that cannot be proven by the compiler.

Whether you agree with that definition is something else entirely, but that is the definition.

**Comment by user471** [comment]
I don't agree with generalization of this definition. Exception and unexpected behavior are two completely different types of unsafety. The first one is reasonable to work with and another is nightmare for debuging. So, they should be separated.
On other hand, why does unexpected behavior even exists? For high performance? Who cares about high perfomance in ps where there are several layers of abstraction over js? If you have a performance problem in a part of your application you can just rewrite this part with pure js.

**Comment by garyb** [comment]
Unsafe is unsafe.
