### ISSUE TITLE
Recover replicate

### ISSUE THREAD

**Issue by jutaro** [purescript/purescript-arrays#67]
Replicate has been removed. But it was useful and efficient. Can you show me an alternative way with equal or better performance? Otherwise please undo this change

**Comment by garyb** [comment]
It's in `purescript-unfoldable` now.

**Comment by jutaro** [comment]
What do you guess, how much worse will the performance be? 10 times, 100 times?

**Comment by paf31** [comment]
A separate library of monomorphic array functions would probably be a good idea. Or even a whole monomorphic Prelude.

This comes down to the direction we want the core libraries to take. Personally, I'd rather have the generic versions, and wait for inlining in `psc-bundle`, but then raw speed was never a concern for me. I appreciate that your use case is different, and I'd be interested to understand how you're using the core libraries. If you don't use very much, you could build a custom Prelude. Then you won't have to worry about library compatibility.

**Comment by garyb** [comment]
It will depend on the size I imagine. Since you asked, my guess is a it's roughly a gajillion times worse on average.

Sarcasm aside, I'm not entirely unsympathetic to your point. I'd prefer not to clutter up the standard libraries with alternative versions of functions for the sake of performance though, since most people won't need them, and the resulting code will be over-specialised. Not to mention in the case here, it was implemented in the FFI if I remember rightly, so means it would be more work for other backends to support this library.

Once we have default implementations for classes it gives us some more options, as we could move most functions on data structures into classes, use the current implementations as the defaults, and then still have the option to provide efficient specific implementations. 

For now we could start a `purescript-arrays-fast` repo in contrib perhaps, or something like that.

**Comment by mgmeier** [comment]
> [...] or the sake of performance though, since most people won't need them
@garyb And how do you come to that assessment?

**Comment by garyb** [comment]
Well, it's based on a lack of evidence rather than positive proof; I don't see much talk about people using PureScript for performance critical applications. Since it's open source maybe there are a horde of silent people out there using it for real time graphics and the like, but I doubt it, there are many other performance issues to complain about too, so we'd probably have more feedback on that.

There's the old adage about premature optimisation too.

I'm not saying performance is unimportant, but also when it is really important the needs are going to differ than what is good for general purpose. Generally we prefer to be abstract. If we start providing less polymorphic versions of everything for performance's sake, we're discouraging something that we think is generally good, which sends mixed messages. One of the ideas behind the way we do the PS libraries is you don't _have_ to use the "official" ecosystem if you don't like it. This seems like a perfect example of where an alternative library would be useful, as it would suit the needs of a specific case better.

**Comment by jutaro** [comment]
Just tested it, the new replicate implementation is only about 20 times slower

**Comment by jutaro** [comment]
Ok, face it, an array operation which is 20 times slower is a disaster!

**Comment by garyb** [comment]
It's back in 2.0.
