### ISSUE TITLE
Rename indexImpl to indexMaybe and export it

### ISSUE THREAD

**Issue by MaiaVictor** [purescript/purescript-arrays#69]
I think the exported `index` function has terrible performance for such a low level operation, and adds unnecessary code complexity where it is used. I suggest renaming `indexImpl` to `indexMaybe` and exporting it. This way, one could define, for example:

    indexInt :: Array Int -> Int -> Int
    indexInt = indexMaybe id 0

And similar, which are much more convenient, readable and faster versions of `index`. 

I will submit a PR if agreed.

**Comment by garyb** [comment]
If performance is a concern then a bounds-check-protected `unsafeIndex` should probably be used.

**Comment by MaiaVictor** [comment]
That works too. Can I submit a PR?

**Comment by garyb** [comment]
I'm not sure... it's not a bad idea, but it's perhaps a slippery slope to "why not export all similar functions with a fold-style signature"? By that I mean the a general but equivalent version of `indexImpl`:

``` purescript
index' ∷ ∀ a r. (a → r) → r → Array a → Int → r
```

Which could then be used for `indexInt` directly:

``` purescript
indexInt = index' id 0
```

There's nothing wrong with that, but I don't know if it's the way we'd want to go, since you could argue that it's no easier than just defining:

``` purescript
indexInt xs = maybe 0 <<< index xs
```

It seems like maybe the wrong level of abstraction for the standard interface? I dunno.
